### PR TITLE
Fix tapping bug for iPhone X

### LINKED ISSUE #36: Cannot tap in-app notifications on iPhone X
This issue is specific to **iPhone X:** users cannot tap on in-app notifications.

To easily reproduce:
- Create 2 boards
- Open one board, select item(s) and tap "Move"
- A notification will appear at the top of the screan
- Tap it

When taping the notification, the user should be taken to the board view. 
Instead, either nothing happens or the elements under the notifications are taped (like "Share").

### PR DESCRIPTION
**Pull request by AvdLee**
Fixes a bug where notifications weren't tappable.

Fixes #36

### CODE REVIEW

File: UINotificationsTests/UINotificationDefaultElementsTests.swift [hunk 1]
```diff
@@ -105,9 +105,10 @@ final class UINotificationDefaultElementsTests: UINotificationTestCase {
         
         // Wait till the notification is presented
         waitFor(notificationCenter.currentPresenter?.dismissTrigger.target != nil, timeout: 5.0, description: "Dismiss trigger target should be set")
-        
-        XCTAssert(notificationCenter.currentPresenter?.presentationContext.containerWindow.point(inside: CGPoint(x: 0, y: 10), with: nil) == true, "Point inside the notification view should be handled")
-        let notificationViewFrame = notificationCenter.currentPresenter?.presentationContext.notificationView.frame
-        XCTAssert(notificationCenter.currentPresenter?.presentationContext.containerWindow.point(inside: CGPoint(x: 0, y: notificationViewFrame!.height + 10), with: nil) == false, "Point outside the notification view should not be handled")
+
+        let notificationViewFrameOrigin = notificationCenter.currentPresenter!.presentationContext.notificationView.frame.origin
```
Comment (WeTransferOSSBot) [inline UINotificationsTests/UINotificationDefaultElementsTests.swift]: <table data-meta="generated_by_danger">
  <tbody>
    <tr>
      <td>:no_entry_sign:</td>
      <td width="100%" data-sticky="false"><span data-href="https://github.com/WeTransfer/UINotifications/blob/79c32c72664a8b042a90304649b0da5fcf9177a1/UINotificationsTests/UINotificationDefaultElementsTests.swift#L109"></span>Force unwrapping should be avoided.</td>
    </tr>
  </tbody>
</table>

Comment (Boris-Em) [reply UINotificationsTests/UINotificationDefaultElementsTests.swift]: This is fine for tests, right?
